---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ephemeral-ssd
  namespace: beagclave-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/arch
    values: ["amd64"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ephemeral-nfs
  namespace: beagclave-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cui-data-storage
  namespace: beagclave-cui-data
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
parameters:
  skuname: default
  kind: Managed
  storageAccountAttributes: "sku-name=Premium_LRS"
  shareName: cui-data-share